import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/wonder.dart';

/// The wonder catalog, loaded once from assets/wonders.json.
///
/// That asset is generated by `node scripts/export-wonders.js` from the
/// TypeScript catalog in ../../lib/wonders/, which stays the single source of
/// truth. Nothing here is hand-maintained; re-run the export after editing a
/// card.
///
/// 178 records is small enough to hold in memory and filter in Dart, which is
/// why this is a JSON asset and the Bible is a database.
class WondersRepository {
  WondersRepository._({
    required this.wonders,
    required this.themeLabels,
    required this.eraLabels,
    required this.eraOrder,
  })  : _byId = {for (final w in wonders) w.id: w},
        _byParallelGroup = _groupParallels(wonders);

  static const _assetPath = 'assets/wonders.json';

  /// The shape scripts/export-wonders.js writes. Refuse to parse anything
  /// newer rather than silently dropping fields.
  static const _supportedSchema = 1;

  final List<Wonder> wonders;
  final Map<WonderTheme, String> themeLabels;
  final Map<WonderEra, String> eraLabels;

  /// Reading order for the era filter.
  final List<WonderEra> eraOrder;

  final Map<String, Wonder> _byId;
  final Map<String, List<Wonder>> _byParallelGroup;

  static WondersRepository? _instance;

  static Future<WondersRepository> load() async {
    final existing = _instance;
    if (existing != null) return existing;

    final raw = await rootBundle.loadString(_assetPath);
    final json = jsonDecode(raw) as Map<String, dynamic>;

    final schema = (json['schemaVersion'] as num?)?.toInt() ?? 0;
    if (schema > _supportedSchema) {
      throw StateError(
        'assets/wonders.json is schema v$schema but this build understands '
        'v$_supportedSchema. Update lib/models/wonder.dart and bump '
        '_supportedSchema.',
      );
    }

    return _instance = WondersRepository._(
      wonders: (json['wonders'] as List<dynamic>)
          .map((e) => Wonder.fromJson(e as Map<String, dynamic>))
          .toList(),
      themeLabels: _labelMap(
        json['themeLabels'] as Map<String, dynamic>?,
        WonderTheme.parse,
      ),
      eraLabels: _labelMap(
        json['eraLabels'] as Map<String, dynamic>?,
        WonderEra.parse,
      ),
      eraOrder: (json['eraOrder'] as List<dynamic>?)
              ?.map((e) => WonderEra.parse(e as String))
              .toList() ??
          WonderEra.values,
    );
  }

  static Map<T, String> _labelMap<T>(
    Map<String, dynamic>? raw,
    T Function(String) parse,
  ) {
    if (raw == null) return {};
    return {
      for (final entry in raw.entries) parse(entry.key): entry.value as String,
    };
  }

  static Map<String, List<Wonder>> _groupParallels(List<Wonder> wonders) {
    final groups = <String, List<Wonder>>{};
    for (final w in wonders) {
      final group = w.parallelGroupId;
      if (group != null) groups.putIfAbsent(group, () => []).add(w);
    }
    return groups;
  }

  int get count => wonders.length;

  Wonder? byId(String id) => _byId[id];

  List<Wonder> get authored => wonders.where((w) => w.authored).toList();

  /// The other accounts of the same event — what "Also in Matthew · Luke"
  /// links to. Excludes [wonder] itself.
  List<Wonder> parallelsOf(Wonder wonder) {
    final group = wonder.parallelGroupId;
    if (group == null) return const [];
    return (_byParallelGroup[group] ?? const [])
        .where((w) => w.id != wonder.id)
        .toList();
  }

  /// Best-known first. Unranked wonders keep Bible order behind the ranked
  /// ones rather than being dropped.
  List<Wonder> byFamiliarity([List<Wonder>? source]) {
    final list = [...(source ?? wonders)];
    list.sort((a, b) {
      final ra = a.familiarityRank;
      final rb = b.familiarityRank;
      if (ra != null && rb != null) return ra.compareTo(rb);
      if (ra != null) return -1;
      if (rb != null) return 1;
      return 0;
    });
    return list;
  }

  /// The Start Here shortlist: the ranked wonders, best-known first.
  List<Wonder> startHere({int limit = 25}) =>
      byFamiliarity(wonders.where((w) => w.isRanked).toList()).take(limit).toList();

  List<Wonder> byTheme(WonderTheme theme) =>
      wonders.where((w) => w.theme == theme).toList();

  List<Wonder> byEra(WonderEra era) =>
      wonders.where((w) => w.era == era).toList();

  /// Eras that actually have wonders, in reading order — so the era picker
  /// never offers an empty filter.
  List<WonderEra> populatedEras() {
    final present = wonders.map((w) => w.era).toSet();
    return eraOrder.where(present.contains).toList();
  }

  /// Title, location and passage label. Deliberately not the card prose: a
  /// search for "sea" should find the sea crossings, not every card that
  /// mentions one in passing.
  List<Wonder> search(String query) {
    final needle = _normalise(query);
    if (needle.isEmpty) return const [];
    return wonders.where((w) {
      return _normalise(w.title).contains(needle) ||
          _normalise(w.passage.label).contains(needle) ||
          _normalise(w.location ?? '').contains(needle);
    }).toList();
  }

  /// The WEB text and the card titles disagree about apostrophe style, so
  /// fold both forms together before comparing.
  static String _normalise(String s) =>
      s.toLowerCase().replaceAll(RegExp(r"['’]"), '').trim();

  String labelFor(WonderTheme theme) => themeLabels[theme] ?? theme.id;
  String labelForEra(WonderEra era) => eraLabels[era] ?? era.id;
}
