/**
 * Master index — New Testament.
 *
 * Locked scope rule: a shared event told by more than one Gospel is more than
 * one wonder here. Each account is its own row with its own passage, tied to
 * its siblings by `parallelGroupId`, so a card can say "Also in Matthew · Luke"
 * and so each account can later stress what *its* writer saw (rule (a)).
 *
 * Ids for parallel accounts are suffixed with the book: `-mat`, `-mrk`,
 * `-luk`, `-jhn`.
 */

import { ref } from '@/lib/passages'
import type { Wonder } from './types'

export const NEW_TESTAMENT_WONDERS: Wonder[] = [
  /* --- Matthew ---------------------------------------------------------- */
  {
    id: 'leper-cleansed-mat',
    title: 'A Man with Leprosy Cleansed',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '8', 1, 4),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'leper-cleansed',
  },
  {
    id: 'centurions-servant-mat',
    title: "The Centurion's Servant",
    testament: 'new',
    passage: ref('MAT', 'Matthew', '8', 5, 13),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'centurions-servant',
  },
  {
    id: 'peters-mother-in-law-mat',
    title: "Peter's Mother-in-Law Healed",
    testament: 'new',
    passage: ref('MAT', 'Matthew', '8', 14, 15),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'peters-mother-in-law',
  },
  {
    id: 'calming-storm-mat',
    title: 'The Storm Stilled',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '8', 23, 27),
    theme: 'nature',
    era: 'matthew',
    parallelGroupId: 'calming-storm',
  },
  {
    id: 'gerasene-demoniac-mat',
    title: 'The Demoniacs among the Tombs',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '8', 28, 34),
    theme: 'rescue',
    era: 'matthew',
    parallelGroupId: 'gerasene-demoniac',
  },
  {
    id: 'paralytic-mat',
    title: 'The Paralysed Man Forgiven and Healed',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '9', 1, 8),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'paralytic',
  },
  {
    id: 'bleeding-woman-mat',
    title: 'The Woman Who Touched His Cloak',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '9', 20, 22),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'bleeding-woman',
  },
  {
    id: 'jairus-daughter-mat',
    title: "The Ruler's Daughter Raised",
    testament: 'new',
    passage: ref('MAT', 'Matthew', '9', 23, 26),
    theme: 'raising',
    era: 'matthew',
    parallelGroupId: 'jairus-daughter',
  },
  {
    id: 'two-blind-men-mat',
    title: 'Two Blind Men Follow Him',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '9', 27, 31),
    theme: 'healing',
    era: 'matthew',
  },
  {
    id: 'mute-demoniac-mat',
    title: 'The Mute Man Speaks',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '9', 32, 34),
    theme: 'healing',
    era: 'matthew',
  },
  {
    id: 'withered-hand-mat',
    title: 'The Withered Hand Restored',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '12', 9, 13),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'withered-hand',
  },
  {
    id: 'blind-mute-demoniac-mat',
    title: 'A Blind and Mute Man Healed',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '12', 22, 23),
    theme: 'healing',
    era: 'matthew',
  },
  {
    id: 'feeding-5000-mat',
    title: 'Five Thousand Fed',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '14', 13, 21),
    theme: 'provision',
    era: 'matthew',
    parallelGroupId: 'feeding-5000',
  },
  {
    id: 'walking-on-water-mat',
    title: 'Walking on the Water',
    location: 'The Sea of Galilee, in the fourth watch of the night',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '14', 25, 31),
    theme: 'nature',
    era: 'matthew',
    parallelGroupId: 'walking-on-water',
    familiarityRank: 3,
    quote:
      'Immediately Jesus stretched out His hand, took hold of Him, and said to Him, "You of little faith, why did you doubt?"',
    quoteRef: 'Matthew 14:31',
    details: [
      'The disciples were miles from shore, fighting strong headwinds, when they saw a figure walking toward them on the sea.',
      'Peter is the only one who asked to try it himself — and he did walk, for a moment.',
      'He only began to sink once he noticed the wind and got afraid, not before.',
    ],
    whatHappened:
      'Exhausted from rowing against the wind all night, the disciples saw what they thought was a ghost walking toward their boat across the water. It was Jesus. Peter asked to come out and meet him — and for a few steps, he did — until he noticed how strong the wind was and started to sink.',
    hopeMeaning:
      "Peter didn't fail because he tried. He only faltered once his attention moved from Jesus to the size of the wind. The hand that caught him was already reaching out before he'd even finished asking for help.",
    reflectionQuestion:
      "What are you looking at right now — the wind, or the hand that's already reaching for you?",
    distinctive:
      'Only Matthew puts Peter over the side. Mark keeps the disciples in the boat and ends on hearts that still did not understand; John has the boat simply arrive at the shore. Matthew alone tells of someone who asked to come, managed it, looked at the wind, went under, and was caught — which makes this the account about faith that starts and falters rather than faith that never began.',
  },
  {
    id: 'canaanite-daughter-mat',
    title: "The Canaanite Woman's Daughter",
    testament: 'new',
    passage: ref('MAT', 'Matthew', '15', 21, 28),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'canaanite-daughter',
  },
  {
    id: 'feeding-4000-mat',
    title: 'Four Thousand Fed',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '15', 32, 39),
    theme: 'provision',
    era: 'matthew',
    parallelGroupId: 'feeding-4000',
  },
  {
    id: 'transfiguration-mat',
    title: 'The Transfiguration',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '17', 1, 8),
    theme: 'sign',
    era: 'matthew',
    parallelGroupId: 'transfiguration',
    familiarityRank: 18,
  },
  {
    id: 'boy-with-demon-mat',
    title: 'The Boy His Disciples Could Not Help',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '17', 14, 21),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'boy-with-demon',
  },
  {
    id: 'coin-in-the-fish-mat',
    title: 'The Coin in the Fish',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '17', 24, 27),
    theme: 'provision',
    era: 'matthew',
  },
  {
    id: 'blind-at-jericho-mat',
    title: 'Two Blind Men at Jericho',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '20', 29, 34),
    theme: 'healing',
    era: 'matthew',
    parallelGroupId: 'blind-at-jericho',
  },
  {
    id: 'fig-tree-mat',
    title: 'The Fig Tree Withers',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '21', 18, 22),
    theme: 'sign',
    era: 'matthew',
    parallelGroupId: 'fig-tree',
  },
  {
    id: 'resurrection-mat',
    title: 'He Is Risen',
    testament: 'new',
    passage: ref('MAT', 'Matthew', '28', 1, 10),
    theme: 'raising',
    era: 'matthew',
    parallelGroupId: 'resurrection',
  },

  /* --- Mark ------------------------------------------------------------- */
  {
    id: 'demoniac-in-synagogue-mrk',
    title: 'The Man in the Synagogue',
    testament: 'new',
    passage: ref('MRK', 'Mark', '1', 21, 28),
    theme: 'rescue',
    era: 'mark',
    parallelGroupId: 'demoniac-in-synagogue',
  },
  {
    id: 'peters-mother-in-law-mrk',
    title: "Peter's Mother-in-Law Healed",
    testament: 'new',
    passage: ref('MRK', 'Mark', '1', 29, 31),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'peters-mother-in-law',
  },
  {
    id: 'leper-cleansed-mrk',
    title: 'A Man with Leprosy Cleansed',
    testament: 'new',
    passage: ref('MRK', 'Mark', '1', 40, 45),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'leper-cleansed',
  },
  {
    id: 'paralytic-mrk',
    title: 'The Man Let Down through the Roof',
    testament: 'new',
    passage: ref('MRK', 'Mark', '2', 1, 12),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'paralytic',
  },
  {
    id: 'withered-hand-mrk',
    title: 'The Withered Hand Restored',
    testament: 'new',
    passage: ref('MRK', 'Mark', '3', 1, 6),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'withered-hand',
  },
  {
    id: 'calming-storm-mrk',
    title: 'The Storm Stilled',
    location: 'The Sea of Galilee, in a boat at evening',
    testament: 'new',
    passage: ref('MRK', 'Mark', '4', 37, 41),
    theme: 'nature',
    era: 'mark',
    parallelGroupId: 'calming-storm',
    familiarityRank: 11,
    quote:
      'He awoke and rebuked the wind, and said to the sea, "Peace! Be still!" The wind ceased and there was a great calm.',
    quoteRef: 'Mark 4:39',
    details: [
      'The storm was strong enough that experienced fishermen were convinced they were about to die.',
      'Jesus was asleep in the boat, seemingly unbothered by the same waves terrifying everyone else.',
      "He didn't calm the disciples first — he spoke directly to the wind and the water.",
    ],
    whatHappened:
      'Caught in a sudden, violent storm on the lake, the disciples — several of them experienced fishermen — panicked and woke Jesus, convinced the boat was going down. He stood up, spoke three words to the storm, and the wind and waves went completely still.',
    hopeMeaning:
      "What's easy to miss is that Jesus was in the boat the whole time, storm and all — just asleep. Hope doesn't always mean the danger never touches you. Sometimes it means the one who can calm it was already there before you noticed.",
    reflectionQuestion:
      'In your current storm, does it feel like you\'re facing it alone — or is it possible help has been closer than you realized?',
    distinctive:
      'Mark is the blunt one. Matthew has the disciples cry "Save us, Lord!" and Luke "Master, Master" — Mark has them accuse him: "Teacher, don\'t you care that we are dying?" Mark alone notes he was asleep on the cushion, and alone gives the words spoken to the sea: "Peace! Be still!" This is the account where the disciples are not merely frightened but convinced they have been abandoned, and say so to his face.',
  },
  {
    id: 'gerasene-demoniac-mrk',
    title: 'The Man Called Legion',
    testament: 'new',
    passage: ref('MRK', 'Mark', '5', 1, 20),
    theme: 'rescue',
    era: 'mark',
    parallelGroupId: 'gerasene-demoniac',
  },
  {
    id: 'bleeding-woman-mrk',
    title: 'The Woman Who Touched His Cloak',
    location: 'A crowded street in Galilee, on the way to a dying girl',
    testament: 'new',
    passage: ref('MRK', 'Mark', '5', 25, 34),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'bleeding-woman',
    familiarityRank: 12,
    quote:
      'Daughter, your faith has made you well. Go in peace, and be cured of your disease.',
    quoteRef: 'Mark 5:34',
    details: [
      'She had been ill for twelve years, and had spent everything she owned on doctors, only to get worse.',
      "She didn't ask Jesus for anything out loud — she reached through the crowd and touched the edge of his clothing.",
      'Jesus stopped and looked for her specifically, even in a crowd pressing in from every side.',
    ],
    whatHappened:
      'A woman who had suffered a chronic illness for twelve years — and spent everything she had trying to get better — pushed through a dense crowd, too afraid or ashamed to ask out loud, and just touched the edge of Jesus\'s cloak. She was healed instantly, and Jesus stopped to find her.',
    hopeMeaning:
      "Twelve years of being unseen, unheard, and overlooked ends with Jesus stopping an entire crowd just to notice her. Hope isn't only for the miracles everyone is watching. It reaches the person who was too tired, or too embarrassed, to ask for help out loud.",
    reflectionQuestion:
      "Is there a need you've been carrying quietly, too tired or embarrassed to say out loud?",
    distinctive:
      'Mark gives her the longest and least flattering medical history: she had suffered many things at the hands of many physicians, spent everything she had, and was no better but rather grew worse. Matthew tells it in three verses and has Jesus simply turn and see her; Luke keeps the doctors but not the detail that they made her worse. Mark is the account for anyone whose treatment has cost them everything and left them further back than they started.',
  },
  {
    id: 'jairus-daughter-mrk',
    title: "Jairus' Daughter Raised",
    testament: 'new',
    passage: ref('MRK', 'Mark', '5', 35, 43),
    theme: 'raising',
    era: 'mark',
    parallelGroupId: 'jairus-daughter',
    familiarityRank: 21,
  },
  {
    id: 'feeding-5000-mrk',
    title: 'Five Thousand Fed',
    testament: 'new',
    passage: ref('MRK', 'Mark', '6', 30, 44),
    theme: 'provision',
    era: 'mark',
    parallelGroupId: 'feeding-5000',
  },
  {
    id: 'walking-on-water-mrk',
    title: 'Walking on the Water',
    testament: 'new',
    passage: ref('MRK', 'Mark', '6', 45, 52),
    theme: 'nature',
    era: 'mark',
    parallelGroupId: 'walking-on-water',
  },
  {
    id: 'canaanite-daughter-mrk',
    title: "The Syrophoenician Woman's Daughter",
    testament: 'new',
    passage: ref('MRK', 'Mark', '7', 24, 30),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'canaanite-daughter',
  },
  {
    id: 'deaf-and-mute-mrk',
    title: 'The Deaf Man Whose Ears Were Opened',
    testament: 'new',
    passage: ref('MRK', 'Mark', '7', 31, 37),
    theme: 'healing',
    era: 'mark',
  },
  {
    id: 'feeding-4000-mrk',
    title: 'Four Thousand Fed',
    testament: 'new',
    passage: ref('MRK', 'Mark', '8', 1, 10),
    theme: 'provision',
    era: 'mark',
    parallelGroupId: 'feeding-4000',
  },
  {
    id: 'blind-at-bethsaida-mrk',
    title: 'The Blind Man at Bethsaida',
    testament: 'new',
    passage: ref('MRK', 'Mark', '8', 22, 26),
    theme: 'healing',
    era: 'mark',
  },
  {
    id: 'transfiguration-mrk',
    title: 'The Transfiguration',
    testament: 'new',
    passage: ref('MRK', 'Mark', '9', 2, 8),
    theme: 'sign',
    era: 'mark',
    parallelGroupId: 'transfiguration',
  },
  {
    id: 'boy-with-demon-mrk',
    title: 'The Boy His Disciples Could Not Help',
    testament: 'new',
    passage: ref('MRK', 'Mark', '9', 14, 29),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'boy-with-demon',
  },
  {
    id: 'blind-at-jericho-mrk',
    title: 'Blind Bartimaeus',
    testament: 'new',
    passage: ref('MRK', 'Mark', '10', 46, 52),
    theme: 'healing',
    era: 'mark',
    parallelGroupId: 'blind-at-jericho',
    familiarityRank: 22,
  },
  {
    id: 'fig-tree-mrk',
    title: 'The Fig Tree Withers',
    testament: 'new',
    passage: ref('MRK', 'Mark', '11', 12, 14),
    theme: 'sign',
    era: 'mark',
    parallelGroupId: 'fig-tree',
    alsoSee: [ref('MRK', 'Mark', '11', 20, 25)],
  },
  {
    id: 'resurrection-mrk',
    title: 'He Is Risen',
    testament: 'new',
    passage: ref('MRK', 'Mark', '16', 1, 8),
    theme: 'raising',
    era: 'mark',
    parallelGroupId: 'resurrection',
  },

  /* --- Luke ------------------------------------------------------------- */
  {
    id: 'demoniac-in-synagogue-luk',
    title: 'The Man in the Synagogue',
    testament: 'new',
    passage: ref('LUK', 'Luke', '4', 31, 37),
    theme: 'rescue',
    era: 'luke',
    parallelGroupId: 'demoniac-in-synagogue',
  },
  {
    id: 'peters-mother-in-law-luk',
    title: "Peter's Mother-in-Law Healed",
    testament: 'new',
    passage: ref('LUK', 'Luke', '4', 38, 39),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'peters-mother-in-law',
  },
  {
    id: 'catch-of-fish-luk',
    title: 'The Nets That Began to Break',
    testament: 'new',
    passage: ref('LUK', 'Luke', '5', 1, 11),
    theme: 'provision',
    era: 'luke',
  },
  {
    id: 'leper-cleansed-luk',
    title: 'A Man Full of Leprosy Cleansed',
    testament: 'new',
    passage: ref('LUK', 'Luke', '5', 12, 16),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'leper-cleansed',
  },
  {
    id: 'paralytic-luk',
    title: 'The Man Let Down through the Tiles',
    testament: 'new',
    passage: ref('LUK', 'Luke', '5', 17, 26),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'paralytic',
  },
  {
    id: 'withered-hand-luk',
    title: 'The Withered Hand Restored',
    testament: 'new',
    passage: ref('LUK', 'Luke', '6', 6, 11),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'withered-hand',
  },
  {
    id: 'centurions-servant-luk',
    title: "The Centurion's Servant",
    testament: 'new',
    passage: ref('LUK', 'Luke', '7', 1, 10),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'centurions-servant',
  },
  {
    id: 'widows-son-at-nain-luk',
    title: "The Widow's Son at Nain",
    testament: 'new',
    passage: ref('LUK', 'Luke', '7', 11, 17),
    theme: 'raising',
    era: 'luke',
  },
  {
    id: 'calming-storm-luk',
    title: 'The Storm Stilled',
    testament: 'new',
    passage: ref('LUK', 'Luke', '8', 22, 25),
    theme: 'nature',
    era: 'luke',
    parallelGroupId: 'calming-storm',
  },
  {
    id: 'gerasene-demoniac-luk',
    title: 'The Man Called Legion',
    testament: 'new',
    passage: ref('LUK', 'Luke', '8', 26, 39),
    theme: 'rescue',
    era: 'luke',
    parallelGroupId: 'gerasene-demoniac',
  },
  {
    id: 'bleeding-woman-luk',
    title: 'The Woman Who Touched His Cloak',
    testament: 'new',
    passage: ref('LUK', 'Luke', '8', 43, 48),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'bleeding-woman',
  },
  {
    id: 'jairus-daughter-luk',
    title: "Jairus' Daughter Raised",
    testament: 'new',
    passage: ref('LUK', 'Luke', '8', 49, 56),
    theme: 'raising',
    era: 'luke',
    parallelGroupId: 'jairus-daughter',
  },
  {
    id: 'feeding-5000-luk',
    title: 'Five Thousand Fed',
    testament: 'new',
    passage: ref('LUK', 'Luke', '9', 10, 17),
    theme: 'provision',
    era: 'luke',
    parallelGroupId: 'feeding-5000',
  },
  {
    id: 'transfiguration-luk',
    title: 'The Transfiguration',
    testament: 'new',
    passage: ref('LUK', 'Luke', '9', 28, 36),
    theme: 'sign',
    era: 'luke',
    parallelGroupId: 'transfiguration',
  },
  {
    id: 'boy-with-demon-luk',
    title: 'The Boy His Disciples Could Not Help',
    testament: 'new',
    passage: ref('LUK', 'Luke', '9', 37, 43),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'boy-with-demon',
  },
  {
    id: 'crippled-woman-luk',
    title: 'The Woman Bent Double for Eighteen Years',
    testament: 'new',
    passage: ref('LUK', 'Luke', '13', 10, 17),
    theme: 'healing',
    era: 'luke',
  },
  {
    id: 'man-with-dropsy-luk',
    title: 'The Man with Dropsy',
    testament: 'new',
    passage: ref('LUK', 'Luke', '14', 1, 6),
    theme: 'healing',
    era: 'luke',
  },
  {
    id: 'ten-lepers-luk',
    title: 'Ten Healed, One Returns',
    testament: 'new',
    passage: ref('LUK', 'Luke', '17', 11, 19),
    theme: 'healing',
    era: 'luke',
  },
  {
    id: 'blind-at-jericho-luk',
    title: 'The Blind Man near Jericho',
    testament: 'new',
    passage: ref('LUK', 'Luke', '18', 35, 43),
    theme: 'healing',
    era: 'luke',
    parallelGroupId: 'blind-at-jericho',
  },
  {
    id: 'severed-ear-luk',
    title: 'The Severed Ear Restored',
    testament: 'new',
    passage: ref('LUK', 'Luke', '22', 50, 51),
    theme: 'healing',
    era: 'luke',
  },
  {
    id: 'resurrection-luk',
    title: 'He Is Risen',
    testament: 'new',
    passage: ref('LUK', 'Luke', '24', 1, 12),
    theme: 'raising',
    era: 'luke',
    parallelGroupId: 'resurrection',
  },

  /* --- John ------------------------------------------------------------- */
  {
    id: 'cana',
    title: 'Water into Wine at Cana',
    location: 'A wedding in Cana of Galilee',
    testament: 'new',
    passage: ref('JHN', 'John', '2', 1, 11),
    theme: 'provision',
    era: 'john',
    familiarityRank: 5,
    quote:
      'Everyone serves the good wine first, and when the guests have drunk freely, then that which is worse. You have kept the good wine until now!',
    quoteRef: 'John 2:10',
    details: [
      'Running out of wine mid-celebration was a real social embarrassment for the family hosting.',
      'Jesus\'s mother didn\'t ask for a miracle — she just told the servants, "Whatever he says to you, do it."',
      'Six large stone jars — roughly 120 to 180 gallons in total — were filled with water, and it came out as wine.',
    ],
    whatHappened:
      'At a wedding, the wine ran out — a small disaster by any measure, but an embarrassing one for the family hosting it. Jesus told the servants to fill enormous stone water jars, and when they poured a cup out to serve, it had become wine — and remarkably good wine at that.',
    hopeMeaning:
      "Not every miracle in this tour starts with someone in mortal danger. This one starts with an ordinary problem on an ordinary day. It shows something worth remembering: the same power that can split a sea is also willing to show up for a wedding that's about to be quietly ruined.",
    reflectionQuestion:
      "Do you only bring the big crises to God, or is there a small, ordinary worry you've been carrying alone?",
  },
  {
    id: 'nobleman-son-jhn',
    title: "The Nobleman's Son Healed from Afar",
    testament: 'new',
    passage: ref('JHN', 'John', '4', 46, 54),
    theme: 'healing',
    era: 'john',
  },
  {
    id: 'bethesda-jhn',
    title: 'The Man at the Pool of Bethesda',
    testament: 'new',
    passage: ref('JHN', 'John', '5', 1, 15),
    theme: 'healing',
    era: 'john',
  },
  {
    id: 'feeding-5000-jhn',
    title: 'Five Thousand Fed',
    location: 'A hillside on the far side of the Sea of Galilee',
    testament: 'new',
    passage: ref('JHN', 'John', '6', 9, 13),
    theme: 'provision',
    era: 'john',
    parallelGroupId: 'feeding-5000',
    familiarityRank: 2,
    quote:
      'Jesus took the loaves, and having given thanks, He distributed to the disciples, and the disciples to those who were sitting down, likewise also of the fish as much as they desired.',
    quoteRef: 'John 6:11',
    details: [
      "The only food anyone could find was a boy's small lunch — five barley loaves and two fish.",
      'More than five thousand people ate until they were full.',
      "Afterward, the leftovers filled twelve baskets — more than they'd started with.",
    ],
    whatHappened:
      'A crowd of thousands had followed Jesus out to a remote hillside with no food and no way to buy any. A boy offered up his small lunch — five loaves, two fish — and Jesus used it to feed the entire crowd, with baskets of food left over.',
    hopeMeaning:
      "The miracle didn't start with abundance. It started with one child's small lunch, offered without knowing what it would become. Hope often begins the same way — not with enough, but with whatever little you actually have, handed over.",
    reflectionQuestion:
      "What's the \"five loaves and two fish\" in your own hands right now — the small thing that doesn't feel like nearly enough?",
    distinctive:
      'John alone tells you where the food came from: a boy, and barley loaves — the cheapest bread there was. The other three accounts simply record five loaves and two fish appearing. John also alone keeps the instruction afterwards, to gather the broken pieces so that nothing would be lost. In his telling the miracle begins with a child\'s lunch and ends with someone being told to pick up the scraps.',
  },
  {
    id: 'walking-on-water-jhn',
    title: 'Walking on the Water',
    testament: 'new',
    passage: ref('JHN', 'John', '6', 16, 21),
    theme: 'nature',
    era: 'john',
    parallelGroupId: 'walking-on-water',
  },
  {
    id: 'man-born-blind-jhn',
    title: 'The Man Born Blind',
    testament: 'new',
    passage: ref('JHN', 'John', '9', 1, 12),
    theme: 'healing',
    era: 'john',
    familiarityRank: 23,
  },
  {
    id: 'lazarus',
    title: 'Lazarus Called out of the Tomb',
    location: 'Bethany, four days after the funeral',
    testament: 'new',
    passage: ref('JHN', 'John', '11', 39, 44),
    theme: 'raising',
    era: 'john',
    familiarityRank: 4,
    quote: '"Lazarus, come out!"',
    quoteRef: 'John 11:43',
    details: [
      'Jesus arrived four days after Lazarus had died — deliberately, and after his sisters had already sent for him.',
      'Martha\'s first words to Jesus were part grief, part accusation: "if you had been here, my brother wouldn\'t have died."',
      'Lazarus came out still bound hand and foot in his grave wrappings, his face wrapped in a cloth — Jesus had to tell the crowd to untie him.',
    ],
    whatHappened:
      'By the time Jesus reached Bethany, his close friend Lazarus had already been dead and buried for four days — long past any hope of recovery, by every normal measure. Jesus asked for the tomb to be opened, called Lazarus by name, and he walked out alive.',
    hopeMeaning:
      "Jesus didn't arrive in time to prevent the death — he arrived after it, on purpose, and grieved it fully before doing anything about it. Hope here isn't the absence of loss. It's what's still possible even after the moment everyone else has already called \"too late.\"",
    reflectionQuestion:
      "Is there something in your life you've already decided is too late to hope for?",
  },
  {
    id: 'resurrection-jhn',
    title: 'He Is Risen',
    testament: 'new',
    passage: ref('JHN', 'John', '20', 1, 18),
    theme: 'raising',
    era: 'john',
    parallelGroupId: 'resurrection',
    familiarityRank: 25,
  },
  {
    id: 'catch-of-153-jhn',
    title: 'Breakfast on the Shore',
    testament: 'new',
    passage: ref('JHN', 'John', '21', 1, 14),
    theme: 'provision',
    era: 'john',
  },

  /* --- Acts and the early church ---------------------------------------- */
  {
    id: 'pentecost',
    title: 'The Day of Pentecost',
    testament: 'new',
    passage: ref('ACT', 'Acts', '2', 1, 4),
    theme: 'sign',
    era: 'acts',
    familiarityRank: 19,
  },
  {
    id: 'lame-man-beautiful-gate',
    title: 'The Lame Man at the Beautiful Gate',
    testament: 'new',
    passage: ref('ACT', 'Acts', '3', 1, 10),
    theme: 'healing',
    era: 'acts',
  },
  {
    id: 'ananias-and-sapphira',
    title: 'Ananias and Sapphira',
    testament: 'new',
    passage: ref('ACT', 'Acts', '5', 1, 11),
    theme: 'judgment',
    era: 'acts',
  },
  {
    id: 'apostles-freed',
    title: 'The Apostles Let out of Prison',
    testament: 'new',
    passage: ref('ACT', 'Acts', '5', 17, 21),
    theme: 'rescue',
    era: 'acts',
  },
  {
    id: 'philip-caught-away',
    title: 'Philip Caught Away',
    testament: 'new',
    passage: ref('ACT', 'Acts', '8', 38, 40),
    theme: 'sign',
    era: 'acts',
  },
  {
    id: 'saul-blinded',
    title: 'The Light on the Damascus Road',
    testament: 'new',
    passage: ref('ACT', 'Acts', '9', 1, 9),
    theme: 'sign',
    era: 'acts',
  },
  {
    id: 'saul-sight-restored',
    title: "Saul's Sight Restored",
    testament: 'new',
    passage: ref('ACT', 'Acts', '9', 17, 19),
    theme: 'healing',
    era: 'acts',
  },
  {
    id: 'aeneas-healed',
    title: 'Aeneas Gets up from His Bed',
    testament: 'new',
    passage: ref('ACT', 'Acts', '9', 32, 35),
    theme: 'healing',
    era: 'acts',
  },
  {
    id: 'tabitha-raised',
    title: 'Tabitha Raised',
    testament: 'new',
    passage: ref('ACT', 'Acts', '9', 36, 42),
    theme: 'raising',
    era: 'acts',
  },
  {
    id: 'peters-rescue',
    title: "Peter's Prison Doors Open",
    location: 'A prison in Jerusalem, the night before his trial',
    testament: 'new',
    passage: ref('ACT', 'Acts', '12', 6, 10),
    theme: 'rescue',
    era: 'acts',
    familiarityRank: 24,
    quote:
      'an angel of the Lord stood by Him, and a light shone in the cell. He struck Peter on the side and woke Him up, saying, "Stand up quickly!" His chains fell off His hands.',
    quoteRef: 'Acts 12:7',
    details: [
      'Peter was guarded by sixteen soldiers and chained between two of them, the night before he was due to be executed.',
      'He was asleep when the angel arrived — not awake and anxiously waiting for rescue.',
      "The prison's iron gate to the city opened on its own, with no one touching it.",
    ],
    whatHappened:
      'The night before Peter was due to be publicly executed, chained between two guards inside a heavily secured prison, an angel appeared, woke him up, and simply told him to get dressed and follow. His chains fell off, the guarded doors opened by themselves, and he walked out into the street.',
    hopeMeaning:
      'This story happens after Jesus had already died and risen — proof the pattern didn\'t stop with him. The same kind of rescue that split a sea and calmed a storm kept showing up for ordinary people in impossible, locked situations, long after the Gospels ended.',
    reflectionQuestion:
      'What locked door in your life feels the most impossible to open right now?',
  },
  {
    id: 'herod-struck',
    title: 'Herod Struck Down',
    testament: 'new',
    passage: ref('ACT', 'Acts', '12', 21, 23),
    theme: 'judgment',
    era: 'acts',
  },
  {
    id: 'elymas-blinded',
    title: 'Elymas Blinded',
    testament: 'new',
    passage: ref('ACT', 'Acts', '13', 6, 12),
    theme: 'judgment',
    era: 'acts',
  },
  {
    id: 'lame-man-at-lystra',
    title: 'The Lame Man at Lystra',
    testament: 'new',
    passage: ref('ACT', 'Acts', '14', 8, 10),
    theme: 'healing',
    era: 'acts',
  },
  {
    id: 'slave-girl-freed',
    title: 'The Slave Girl Who Followed Paul',
    testament: 'new',
    passage: ref('ACT', 'Acts', '16', 16, 18),
    theme: 'rescue',
    era: 'acts',
  },
  {
    id: 'philippi-earthquake',
    title: 'The Earthquake at Philippi',
    testament: 'new',
    passage: ref('ACT', 'Acts', '16', 25, 26),
    theme: 'rescue',
    era: 'acts',
  },
  {
    id: 'pauls-handkerchiefs',
    title: 'Healing at a Distance in Ephesus',
    testament: 'new',
    passage: ref('ACT', 'Acts', '19', 11, 12),
    theme: 'healing',
    era: 'acts',
  },
  {
    id: 'eutychus-raised',
    title: 'Eutychus Raised',
    testament: 'new',
    passage: ref('ACT', 'Acts', '20', 9, 12),
    theme: 'raising',
    era: 'acts',
  },
  {
    id: 'viper-on-malta',
    title: 'The Viper on Malta',
    testament: 'new',
    passage: ref('ACT', 'Acts', '28', 3, 6),
    theme: 'rescue',
    era: 'acts',
  },
  {
    id: 'publius-father-healed',
    title: "Publius' Father Healed",
    testament: 'new',
    passage: ref('ACT', 'Acts', '28', 7, 9),
    theme: 'healing',
    era: 'acts',
  },
]
