/**
 * Master index — Old Testament.
 *
 * Every divine wonder involving people, in Bible order. Card prose is written
 * in batches during Phase 7; these rows carry identity, passage and tags.
 *
 * Locked scope rules (PLAN.md):
 *  - miracles only; vision-only scenes and quiet providence are not here
 *  - the plagues of Egypt are ONE grouped wonder
 *  - borderline signs (burning bush, handwriting on the wall) are included
 *
 * Every reference here is checked against the shipped WEB text by
 * `node scripts/validate-wonders.js`.
 */

import { ref } from '@/lib/passages'
import type { Wonder } from './types'

export const OLD_TESTAMENT_WONDERS: Wonder[] = [
  /* --- Torah ------------------------------------------------------------ */
  {
    id: 'enoch-taken',
    title: 'Enoch Taken by God',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '5', 21, 24),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'the-flood',
    title: 'The Flood',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '7', 17, 24),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'babel',
    title: 'The Languages Confused at Babel',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '11', 1, 9),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'sodom-blindness',
    title: 'The Men of Sodom Struck Blind',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '19', 9, 11),
    theme: 'rescue',
    era: 'torah',
  },
  {
    id: 'sodom-fire',
    title: 'Fire on Sodom and Gomorrah',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '19', 23, 25),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'lots-wife',
    title: "Lot's Wife Becomes a Pillar of Salt",
    testament: 'old',
    passage: ref('GEN', 'Genesis', '19', 26, 26),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'abimelech-healed',
    title: "Abimelech's Household Healed",
    testament: 'old',
    passage: ref('GEN', 'Genesis', '20', 17, 18),
    theme: 'healing',
    era: 'torah',
  },
  {
    id: 'isaac-born',
    title: 'Isaac Born to Sarah',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '21', 1, 3),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'hagar-well',
    title: 'A Well Opened for Hagar',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '21', 15, 19),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'rachel-remembered',
    title: 'Rachel Remembered',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '30', 22, 24),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'jacob-wrestles',
    title: 'Jacob Wrestles until Daybreak',
    testament: 'old',
    passage: ref('GEN', 'Genesis', '32', 24, 32),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'burning-bush',
    title: 'The Burning Bush',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '3', 1, 6),
    theme: 'sign',
    era: 'torah',
    familiarityRank: 14,
  },
  {
    id: 'staff-to-serpent',
    title: "Moses' Staff Becomes a Snake",
    testament: 'old',
    passage: ref('EXO', 'Exodus', '4', 1, 5),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'moses-hand-leprous',
    title: "Moses' Hand Made Leprous and Restored",
    testament: 'old',
    passage: ref('EXO', 'Exodus', '4', 6, 7),
    theme: 'sign',
    era: 'torah',
  },
  {
    // One wonder by design: the ten plagues are a single sustained act. The
    // anchor opens at the first plague; alsoSee walks the rest in order.
    id: 'plagues-of-egypt',
    title: 'The Ten Plagues of Egypt',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '7', 14, 25),
    theme: 'judgment',
    era: 'torah',
    familiarityRank: 15,
    alsoSee: [
      ref('EXO', 'Exodus', '8', 1, 15),
      ref('EXO', 'Exodus', '8', 16, 19),
      ref('EXO', 'Exodus', '8', 20, 32),
      ref('EXO', 'Exodus', '9', 1, 7),
      ref('EXO', 'Exodus', '9', 8, 12),
      ref('EXO', 'Exodus', '9', 13, 35),
      ref('EXO', 'Exodus', '10', 1, 20),
      ref('EXO', 'Exodus', '10', 21, 29),
      ref('EXO', 'Exodus', '12', 29, 32),
    ],
  },
  {
    id: 'pillar-cloud-fire',
    title: 'The Pillar of Cloud and Fire',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '13', 20, 22),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'red-sea',
    title: 'Parting of the Red Sea',
    location: 'The shore of the Red Sea, at the edge of Egypt',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '14', 21, 31),
    theme: 'rescue',
    era: 'torah',
    familiarityRank: 1,
    quote:
      'The children of Israel went into the middle of the sea on the dry ground; and the waters were a wall to them on their right hand and on their left.',
    quoteRef: 'Exodus 14:22',
    details: [
      "Pharaoh's entire army — chariots, horses, soldiers — was closing in from behind, with the sea blocking every other way out.",
      'Moses simply raised his hand, and a strong wind blew all night until the sea floor was dry enough to walk on.',
      'The same waters that opened for Israel closed again over the army chasing them.',
    ],
    whatHappened:
      "The people of Israel had just escaped slavery in Egypt, and now they were trapped — the sea in front of them, Pharaoh's army closing in behind. There was nowhere to run. Then the sea itself opened a path, and an entire nation walked across on dry ground.",
    hopeMeaning:
      "This is the miracle so many other Bible writers point back to, because it says something so simple: the situation that looked completely sealed shut wasn't. When every visible option is gone, that isn't the same as being out of options.",
    reflectionQuestion:
      "Is there a place in your life right now that feels sealed shut on every side — where you can't see a way through?",
  },
  {
    id: 'marah-water',
    title: 'Bitter Water Made Sweet at Marah',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '15', 22, 25),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'manna',
    title: 'Manna from Heaven',
    location: 'The wilderness of Sin, on the way to Sinai',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '16', 4, 15),
    theme: 'provision',
    era: 'torah',
    familiarityRank: 10,
    quote: 'It is the bread which Yahweh has given you to eat.',
    quoteRef: 'Exodus 16:15',
    details: [
      "The people had just complained they'd rather have stayed slaves in Egypt than starve in the desert.",
      'Every morning, a thin flaky substance appeared on the ground with the dew — enough for that day, no more.',
      'It kept appearing every single day for the next forty years, until they no longer needed it.',
    ],
    whatHappened:
      'Free, but hungry, with no fields to farm in the desert, the people ran out of food within weeks of their escape. So a strange bread began appearing on the ground each morning — as much as each family needed for that one day, and no more.',
    hopeMeaning:
      "This isn't a one-time rescue; it's daily provision, repeated for forty years. Hope here doesn't look like one dramatic moment — it looks like showing up again and again, exactly enough, exactly on time.",
    reflectionQuestion:
      'What would it look like to trust for just today, instead of trying to secure your whole future at once?',
  },
  {
    id: 'water-from-rock-horeb',
    title: 'Water from the Rock at Horeb',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '17', 1, 7),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'amalek-defeated',
    title: "Amalek Defeated while Moses' Hands Are Held Up",
    testament: 'old',
    passage: ref('EXO', 'Exodus', '17', 8, 13),
    theme: 'rescue',
    era: 'torah',
  },
  {
    id: 'sinai-descent',
    title: 'Yahweh Descends on Mount Sinai',
    testament: 'old',
    passage: ref('EXO', 'Exodus', '19', 16, 20),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'moses-face-shines',
    title: "Moses' Face Shines",
    testament: 'old',
    passage: ref('EXO', 'Exodus', '34', 29, 35),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'fire-consumes-offering',
    title: 'Fire Consumes the Offering',
    testament: 'old',
    passage: ref('LEV', 'Leviticus', '9', 22, 24),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'nadab-abihu',
    title: 'Nadab and Abihu Consumed',
    testament: 'old',
    passage: ref('LEV', 'Leviticus', '10', 1, 3),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'fire-at-taberah',
    title: 'Fire at Taberah',
    testament: 'old',
    passage: ref('NUM', 'Numbers', '11', 1, 3),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'quail-kibroth',
    title: 'Quail and the Plague at Kibroth Hattaavah',
    testament: 'old',
    passage: ref('NUM', 'Numbers', '11', 31, 34),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'miriam-leprosy',
    title: "Miriam's Leprosy and Healing",
    testament: 'old',
    passage: ref('NUM', 'Numbers', '12', 9, 15),
    theme: 'healing',
    era: 'torah',
  },
  {
    id: 'korah-swallowed',
    title: "The Earth Swallows Korah's Company",
    testament: 'old',
    passage: ref('NUM', 'Numbers', '16', 28, 35),
    theme: 'judgment',
    era: 'torah',
  },
  {
    id: 'aarons-rod-buds',
    title: "Aaron's Rod Buds",
    testament: 'old',
    passage: ref('NUM', 'Numbers', '17', 1, 9),
    theme: 'sign',
    era: 'torah',
  },
  {
    id: 'water-from-rock-meribah',
    title: 'Water from the Rock at Meribah',
    testament: 'old',
    passage: ref('NUM', 'Numbers', '20', 7, 13),
    theme: 'provision',
    era: 'torah',
  },
  {
    id: 'bronze-serpent',
    title: 'The Bronze Serpent',
    testament: 'old',
    passage: ref('NUM', 'Numbers', '21', 4, 9),
    theme: 'healing',
    era: 'torah',
    familiarityRank: 16,
  },
  {
    id: 'balaams-donkey',
    title: "Balaam's Donkey Speaks",
    testament: 'old',
    passage: ref('NUM', 'Numbers', '22', 21, 35),
    theme: 'sign',
    era: 'torah',
  },

  /* --- Conquest and Judges ---------------------------------------------- */
  {
    id: 'jordan-stopped',
    title: 'The Jordan Stops for Israel',
    testament: 'old',
    passage: ref('JOS', 'Joshua', '3', 14, 17),
    theme: 'rescue',
    era: 'conquest',
  },
  {
    id: 'jericho',
    title: 'The Walls of Jericho',
    location: 'Jericho, the first fortified city inside the promised land',
    testament: 'old',
    passage: ref('JOS', 'Joshua', '6', 15, 20),
    theme: 'rescue',
    era: 'conquest',
    familiarityRank: 8,
    quote:
      'When the people heard the sound of the trumpet, the people shouted with a great shout, and the wall fell down flat, so that the people went up into the city, every man straight in front of him, and they took the city.',
    quoteRef: 'Joshua 6:20',
    details: [
      "Jericho's walls were high, thick, and built to withstand a siege — there was no obvious way in.",
      'Instead of attacking, Israel was told to march silently around the city once a day for six days, then seven times on the seventh.',
      'There was no battering ram and no ladder. The walls simply fell, all at once, on cue.',
    ],
    whatHappened:
      "Jericho stood in the way of Israel entering the land they'd been promised — a walled city built to keep armies out. Rather than fighting their way in, Israel was told to walk, in silence, for a week, and then shout. That's it. And the wall came down.",
    hopeMeaning:
      "There's no strategy here a general would recommend. The instructions look pointless right up until the moment they work. Sometimes faith looks exactly like that — doing the small, unimpressive thing you've been asked to do, long before you can see why.",
    reflectionQuestion:
      "Is there something small and unimpressive you keep putting off, because it doesn't look like it could possibly be enough?",
  },
  {
    id: 'hailstones-amorites',
    title: 'Great Stones Fall on the Amorites',
    testament: 'old',
    passage: ref('JOS', 'Joshua', '10', 9, 11),
    theme: 'judgment',
    era: 'conquest',
  },
  {
    id: 'sun-stands-still',
    title: 'The Sun Stands Still over Gibeon',
    testament: 'old',
    passage: ref('JOS', 'Joshua', '10', 12, 14),
    theme: 'nature',
    era: 'conquest',
  },
  {
    id: 'gideon-fire-rock',
    title: 'Fire out of the Rock for Gideon',
    testament: 'old',
    passage: ref('JDG', 'Judges', '6', 19, 24),
    theme: 'sign',
    era: 'conquest',
  },
  {
    id: 'gideon-fleece',
    title: "Gideon's Fleece",
    testament: 'old',
    passage: ref('JDG', 'Judges', '6', 36, 40),
    theme: 'sign',
    era: 'conquest',
  },
  {
    id: 'gideon-three-hundred',
    title: "Gideon's Three Hundred",
    testament: 'old',
    passage: ref('JDG', 'Judges', '7', 19, 22),
    theme: 'rescue',
    era: 'conquest',
  },
  {
    id: 'manoah-flame',
    title: 'The Angel Ascends in the Flame',
    testament: 'old',
    passage: ref('JDG', 'Judges', '13', 15, 21),
    theme: 'sign',
    era: 'conquest',
  },
  {
    id: 'samson-lion',
    title: 'Samson Tears the Lion',
    testament: 'old',
    passage: ref('JDG', 'Judges', '14', 5, 6),
    theme: 'sign',
    era: 'conquest',
  },
  {
    id: 'samson-jawbone',
    title: 'A Thousand Struck with a Jawbone',
    testament: 'old',
    passage: ref('JDG', 'Judges', '15', 14, 17),
    theme: 'rescue',
    era: 'conquest',
  },
  {
    id: 'samson-water',
    title: 'Water from the Hollow Place',
    testament: 'old',
    passage: ref('JDG', 'Judges', '15', 18, 19),
    theme: 'provision',
    era: 'conquest',
  },
  {
    id: 'samson-pillars',
    title: "Samson's Last Strength",
    testament: 'old',
    passage: ref('JDG', 'Judges', '16', 28, 30),
    theme: 'rescue',
    era: 'conquest',
  },

  /* --- Kingdoms --------------------------------------------------------- */
  {
    id: 'hannah-answered',
    title: "Hannah's Prayer Answered",
    testament: 'old',
    passage: ref('1SA', '1 Samuel', '1', 19, 20),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'dagon-falls',
    title: 'Dagon Falls before the Ark',
    testament: 'old',
    passage: ref('1SA', '1 Samuel', '5', 1, 5),
    theme: 'sign',
    era: 'kingdoms',
  },
  {
    id: 'philistine-tumors',
    title: 'Tumors on the Philistines',
    testament: 'old',
    passage: ref('1SA', '1 Samuel', '5', 6, 12),
    theme: 'judgment',
    era: 'kingdoms',
  },
  {
    id: 'thunder-at-mizpah',
    title: 'Thunder at Mizpah',
    testament: 'old',
    passage: ref('1SA', '1 Samuel', '7', 7, 11),
    theme: 'rescue',
    era: 'kingdoms',
  },
  {
    id: 'thunder-in-harvest',
    title: 'Thunder and Rain in Wheat Harvest',
    testament: 'old',
    passage: ref('1SA', '1 Samuel', '12', 16, 18),
    theme: 'sign',
    era: 'kingdoms',
  },
  {
    id: 'uzzah-and-the-ark',
    title: 'Uzzah and the Ark',
    testament: 'old',
    passage: ref('2SA', '2 Samuel', '6', 6, 8),
    theme: 'judgment',
    era: 'kingdoms',
  },
  {
    id: 'census-plague',
    title: "The Plague after David's Census",
    testament: 'old',
    passage: ref('2SA', '2 Samuel', '24', 15, 17),
    theme: 'judgment',
    era: 'kingdoms',
  },
  {
    id: 'jeroboam-hand',
    title: "Jeroboam's Withered Hand Restored",
    testament: 'old',
    passage: ref('1KI', '1 Kings', '13', 1, 6),
    theme: 'healing',
    era: 'kingdoms',
  },
  {
    id: 'ravens-feed-elijah',
    title: 'Ravens Feed Elijah',
    testament: 'old',
    passage: ref('1KI', '1 Kings', '17', 2, 6),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'zarephath-flour-and-oil',
    title: "The Widow's Flour and Oil Do Not Run Out",
    testament: 'old',
    passage: ref('1KI', '1 Kings', '17', 8, 16),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'zarephath-son-raised',
    title: "The Widow's Son Raised at Zarephath",
    testament: 'old',
    passage: ref('1KI', '1 Kings', '17', 17, 24),
    theme: 'raising',
    era: 'kingdoms',
  },
  {
    id: 'elijah-fire',
    title: 'Fire from Heaven at Mount Carmel',
    location: 'Mount Carmel, before all Israel',
    testament: 'old',
    passage: ref('1KI', '1 Kings', '18', 36, 39),
    theme: 'sign',
    era: 'kingdoms',
    familiarityRank: 13,
    quote:
      "Then Yahweh's fire fell and consumed the burnt offering, the wood, the stones, and the dust; and it licked up the water that was in the trench.",
    quoteRef: '1 Kings 18:38',
    details: [
      'Elijah stood alone against 450 prophets of a rival god, in front of a watching crowd.',
      'He soaked his altar in water three times first, to remove any doubt about how it caught fire.',
      'When the fire fell, it consumed rock and water along with the sacrifice.',
    ],
    whatHappened:
      "For years, the nation had been worshiping a foreign god alongside — or instead of — the God of Israel. Elijah, one man against hundreds of the other god's prophets, built an altar, soaked it in water, and prayed a short prayer out loud. Fire fell from the sky and burned it all up — wood, stone, water and all.",
    hopeMeaning:
      "Elijah wasn't hoping for a miracle out of desperation for himself — he was standing alone for something he believed was true, in front of people who thought he was finished. Sometimes hope means being willing to be the only one standing, and trusting that being right doesn't require being popular.",
    reflectionQuestion:
      'When was the last time you held onto what you believed, even though you felt like the only one who did?',
  },
  {
    id: 'elijah-rain',
    title: 'Rain after Three Years of Drought',
    testament: 'old',
    passage: ref('1KI', '1 Kings', '18', 41, 45),
    theme: 'nature',
    era: 'kingdoms',
  },
  {
    id: 'angel-feeds-elijah',
    title: 'An Angel Feeds Elijah',
    testament: 'old',
    passage: ref('1KI', '1 Kings', '19', 5, 8),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'elijah-parts-jordan',
    title: 'Elijah Parts the Jordan',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '2', 7, 8),
    theme: 'nature',
    era: 'kingdoms',
  },
  {
    id: 'elijah-whirlwind',
    title: 'Elijah Taken up in a Whirlwind',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '2', 9, 12),
    theme: 'sign',
    era: 'kingdoms',
  },
  {
    id: 'elisha-parts-jordan',
    title: 'Elisha Parts the Jordan',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '2', 13, 14),
    theme: 'nature',
    era: 'kingdoms',
  },
  {
    id: 'jericho-waters-healed',
    title: 'The Waters of Jericho Healed',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '2', 19, 22),
    theme: 'healing',
    era: 'kingdoms',
  },
  {
    id: 'water-for-the-armies',
    title: 'Water for the Armies in the Desert',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '3', 14, 20),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'widows-oil',
    title: "The Widow's Oil Multiplied",
    testament: 'old',
    passage: ref('2KI', '2 Kings', '4', 1, 7),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'shunammite-son-promised',
    title: 'A Son Promised to the Shunammite',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '4', 11, 17),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'shunammite-son-raised',
    title: "The Shunammite's Son Raised",
    testament: 'old',
    passage: ref('2KI', '2 Kings', '4', 32, 37),
    theme: 'raising',
    era: 'kingdoms',
  },
  {
    id: 'death-in-the-pot',
    title: 'Death in the Pot Made Harmless',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '4', 38, 41),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'feeding-a-hundred',
    title: 'A Hundred Fed with Twenty Loaves',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '4', 42, 44),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'naaman-healed',
    title: 'Naaman Healed of Leprosy',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '5', 1, 14),
    theme: 'healing',
    era: 'kingdoms',
    familiarityRank: 17,
  },
  {
    id: 'gehazi-leprosy',
    title: 'Gehazi Struck with Leprosy',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '5', 20, 27),
    theme: 'judgment',
    era: 'kingdoms',
  },
  {
    id: 'axe-head-floats',
    title: 'The Axe Head Floats',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '6', 1, 7),
    theme: 'provision',
    era: 'kingdoms',
  },
  {
    id: 'chariots-of-fire',
    title: 'Chariots of Fire around Elisha',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '6', 15, 17),
    theme: 'rescue',
    era: 'kingdoms',
  },
  {
    id: 'aramean-army-blinded',
    title: 'The Aramean Army Blinded',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '6', 18, 20),
    theme: 'rescue',
    era: 'kingdoms',
  },
  {
    id: 'elisha-bones',
    title: "A Man Revived on Elisha's Bones",
    testament: 'old',
    passage: ref('2KI', '2 Kings', '13', 20, 21),
    theme: 'raising',
    era: 'kingdoms',
  },
  {
    id: 'assyrian-army-struck',
    title: 'The Assyrian Army Struck by Night',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '19', 32, 36),
    theme: 'rescue',
    era: 'kingdoms',
  },
  {
    id: 'hezekiah-healed',
    title: 'Hezekiah Healed and the Shadow Turned Back',
    testament: 'old',
    passage: ref('2KI', '2 Kings', '20', 1, 11),
    theme: 'healing',
    era: 'kingdoms',
    alsoSee: [ref('ISA', 'Isaiah', '38', 1, 8)],
  },
  {
    id: 'temple-fire',
    title: 'Fire at the Dedication of the Temple',
    testament: 'old',
    passage: ref('2CH', '2 Chronicles', '7', 1, 3),
    theme: 'sign',
    era: 'kingdoms',
  },
  {
    id: 'judahs-enemies-turn',
    title: "Judah's Enemies Destroy One Another",
    testament: 'old',
    passage: ref('2CH', '2 Chronicles', '20', 20, 24),
    theme: 'rescue',
    era: 'kingdoms',
  },
  {
    id: 'uzziah-leprosy',
    title: 'Uzziah Struck with Leprosy',
    testament: 'old',
    passage: ref('2CH', '2 Chronicles', '26', 16, 21),
    theme: 'judgment',
    era: 'kingdoms',
  },

  /* --- Prophets and exile ------------------------------------------------ */
  {
    id: 'jonah-storm',
    title: 'The Storm Sent after Jonah',
    testament: 'old',
    passage: ref('JON', 'Jonah', '1', 4, 16),
    theme: 'nature',
    era: 'prophets',
  },
  {
    id: 'jonah',
    title: 'Jonah and the Great Fish',
    location: 'A ship bound for Tarshish, and the open sea',
    testament: 'old',
    passage: ref('JON', 'Jonah', '1', 15, 17),
    theme: 'rescue',
    era: 'prophets',
    familiarityRank: 9,
    alsoSee: [ref('JON', 'Jonah', '2', 1, 10)],
    quote:
      'Yahweh prepared a huge fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three nights.',
    quoteRef: 'Jonah 1:17',
    details: [
      "Jonah wasn't running toward a disaster — he was running away from a job God had given him.",
      'He was thrown overboard by the sailors as a last resort, expecting to drown.',
      "Three days later, the fish brought him back to dry land, and he finally went where he'd been asked to go.",
    ],
    whatHappened:
      "Told to warn a hostile foreign city, Jonah sailed the opposite direction instead. A storm nearly sank the ship, and Jonah — realizing it was his fault — had the sailors throw him overboard. Rather than letting him drown, God sent a great fish to swallow him, and three days later it left him safely on shore.",
    hopeMeaning:
      "This is the one Old Testament wonder aimed at someone actively running away. It's easy to assume hope is only for people doing everything right. Jonah's story says otherwise: even a second chance, handed to someone mid-flight from their calling, still counts as rescue.",
    reflectionQuestion:
      "Is there something you know you're supposed to be doing, but have been quietly running from?",
  },
  {
    id: 'jonah-plant',
    title: 'The Plant, the Worm and the Wind',
    testament: 'old',
    passage: ref('JON', 'Jonah', '4', 5, 8),
    theme: 'sign',
    era: 'prophets',
  },
  {
    id: 'fiery-furnace',
    title: 'The Fiery Furnace',
    location: 'The plain of Dura, in the province of Babylon',
    testament: 'old',
    passage: ref('DAN', 'Daniel', '3', 16, 27),
    theme: 'rescue',
    era: 'exile',
    familiarityRank: 7,
    quote:
      'Look, I see four men loose, walking in the middle of the fire, and they are unharmed. The appearance of the fourth is like a son of the gods.',
    quoteRef: 'Daniel 3:25',
    details: [
      'Shadrach, Meshach, and Abednego refused to bow to a golden statue, on pain of death.',
      '"If it happens, our God is able to deliver us... but if not, we still won\'t bow" — their answer didn\'t wait for a guaranteed rescue.',
      'The furnace was so hot it killed the guards who threw them in, yet the three men walked around inside it, untouched, with a fourth figure beside them.',
    ],
    whatHappened:
      "Three men refused to worship a statue they didn't believe in, even under threat of being burned alive. The king had them thrown into a furnace heated seven times hotter than normal. When he looked in, expecting to see nothing left, he saw four men walking around, completely unharmed.",
    hopeMeaning:
      '"But if not" is the most remarkable line in this story, and it comes before the miracle. They committed to their faith without knowing whether the rescue was coming. Hope here is not a guarantee that the fire won\'t happen — it\'s the confidence that you won\'t be facing it alone if it does.',
    reflectionQuestion:
      "Could you say \"but if not\" about the thing you're currently hoping for — and still hold on to your faith either way?",
  },
  {
    id: 'nebuchadnezzar-restored',
    title: "Nebuchadnezzar's Madness and Restoration",
    testament: 'old',
    passage: ref('DAN', 'Daniel', '4', 28, 37),
    theme: 'judgment',
    era: 'exile',
  },
  {
    id: 'handwriting-on-the-wall',
    title: 'The Writing on the Wall',
    testament: 'old',
    passage: ref('DAN', 'Daniel', '5', 5, 9),
    theme: 'sign',
    era: 'exile',
    familiarityRank: 20,
  },
  {
    id: 'lions-den',
    title: "Daniel in the Lions' Den",
    location: 'Babylon, under Darius the Mede',
    testament: 'old',
    passage: ref('DAN', 'Daniel', '6', 16, 23),
    theme: 'rescue',
    era: 'exile',
    familiarityRank: 6,
    quote:
      "My God has sent his angel, and has shut the lions' mouths, and they have not hurt me, because innocence was found in me before him; and also before you, O king, I have done no harm.",
    quoteRef: 'Daniel 6:22',
    details: [
      'Daniel kept praying openly, three times a day, even after a law was passed making it a capital offense.',
      'The king who sentenced him spent the whole night fasting, unable to sleep, hoping Daniel would somehow survive.',
      "In the morning, Daniel wasn't just alive — there wasn't a single mark on him.",
    ],
    whatHappened:
      'A group of officials, jealous of Daniel, tricked the king into signing a law that made praying to anyone but the king illegal. Daniel kept praying anyway, exactly as he always had, and was thrown into a den of lions overnight as the penalty. He walked out the next morning completely unharmed.',
    hopeMeaning:
      "Daniel didn't stop an ordinary habit — daily prayer — just because it became dangerous. The miracle wasn't a reward for something dramatic; it was protection over something quietly faithful, repeated for years before anyone was watching that closely.",
    reflectionQuestion:
      'Is there something quietly faithful you keep doing, even when it costs you something to keep doing it?',
  },
]
